<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="prop_mesh_cw" value="package://amarsmer_description/meshes/bluerov2_propcw.dae"/>
  <xacro:property name="prop_mesh_ccw" value="package://amarsmer_description/meshes/bluerov2_propccw.dae"/>
  <xacro:property name="prop_r" value="0.05"/>
  <xacro:property name="prop_l" value="0.035"/>

  <xacro:property name="cylinder_l" value="0.6"/>
  <xacro:property name="cylinder_r" value="0.25"/>

  <!-- Front Ring Link-->
  <link name="${ns}/front_cylinder_ring">
    <visual>
      <!-- Ring wrapped around the cylinder -->
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.22"/>
      </geometry>
      <material name="RingColor">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
  </link>

  <!-- Front Ring Joint-->
  <joint name="${ns}/front_ring_joint" type="revolute">
    <origin xyz="${cylinder_l/4} 0 0" rpy="0 0 0"/>
    <parent link="${ns}/base_link"/>
    <child link="${ns}/front_cylinder_ring"/>
    <axis xyz="1 0 0"/>
    <limit effort="1" velocity="1" lower="-3.14" upper="3.14"/>
  </joint>

  <!-- Back Ring Link-->
  <link name="${ns}/back_cylinder_ring">
    <visual>
      <!-- Ring wrapped around the cylinder -->
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.22"/>
      </geometry>
      <material name="RingColor">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
  </link>

  <!-- Front Ring Joint-->
  <joint name="${ns}/back_ring_joint" type="revolute">
    <origin xyz="-${cylinder_l/2} 0 0" rpy="0 0 0"/>
    <parent link="${ns}/base_link"/>
    <child link="${ns}/back_cylinder_ring"/>
    <axis xyz="1 0 0"/>
    <limit effort="1" velocity="1" lower="-3.14" upper="3.14"/>
  </joint>


  <!-- Thruster macro: link + continuous joint + plugin -->
  <xacro:macro name="thruster" params="thruster_id parent_link *origin">

    <link name="${ns}/thruster${thruster_id}">

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <xacro:if value="${thruster_id in [1,2,5]}">
            <mesh filename="${prop_mesh_cw}"/>
          </xacro:if>
          <xacro:unless value="${thruster_id in [1,2,5]}">
            <mesh filename="${prop_mesh_ccw}"/>
          </xacro:unless>
        </geometry>
      </visual>

      <inertial>
        <origin xyz="${prop_l/2} 0 0" rpy="0 0 0" />
        <mass value="${prop_mass}" />
        <inertia  izz="${prop_mass*prop_r*prop_r / 4  + prop_mass*prop_l*prop_l / 12}" ixy="0.0"  ixz="0.0"
                  iyy="${prop_mass*prop_r*prop_r / 4  + prop_mass*prop_l*prop_l / 12}" iyz="0.0"
                  ixx="${prop_mass*prop_r*prop_r / 2}" />
      </inertial>
    </link>

    <joint name="thruster${thruster_id}" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="1 0 0" />
      <parent link="${parent_link}" />
      <child link="${ns}/thruster${thruster_id}" />
      <limit effort="-1" velocity="-1"/>
    </joint>

    <gazebo>
      <plugin
        filename="ignition-gazebo-thruster-system"
        name="ignition::gazebo::systems::Thruster">
        <namespace>${ns}</namespace>
        <joint_name>thruster${thruster_id}</joint_name>
        <topic>thruster${thruster_id}/cmd</topic>
        <thrust_coefficient>0.011</thrust_coefficient>
        <fluid_density>${density}</fluid_density>
        <propeller_diameter>${2*prop_r}</propeller_diameter>
        <velocity_control>true</velocity_control>
        <use_angvel_cmd>false</use_angvel_cmd>
        <max_thrust_cmd>40</max_thrust_cmd>
        <min_thrust_cmd>-40</min_thrust_cmd>
      </plugin>
    </gazebo>

  </xacro:macro>

  <!-- All 4 thrusters -->
  <xacro:thruster thruster_id="1" parent_link="${ns}/back_cylinder_ring">
    <origin xyz="0 -${cylinder_r} 0" rpy="0 0 0"/>
  </xacro:thruster>

  <xacro:thruster thruster_id="2" parent_link="${ns}/back_cylinder_ring">
    <origin xyz="0 ${cylinder_r} 0" rpy="0 0 0"/>
  </xacro:thruster>

  <xacro:thruster thruster_id="3" parent_link="${ns}/front_cylinder_ring">
    <origin xyz="0 -${cylinder_r} 0" rpy="0 ${pi/2} ${pi}"/>
  </xacro:thruster>

  <xacro:thruster thruster_id="4" parent_link="${ns}/front_cylinder_ring">
    <origin xyz="0 ${cylinder_r} 0" rpy="0 ${pi/2} ${pi}"/>
  </xacro:thruster>

</robot>