/amarsmer/thruster_manager:
  ros__parameters:
    control_frame: amarsmer/base_link
    publish_joint_state: true
    tam:
      deadzone: 1.
      max_thrust: 400.0
      min_thrust: -400.0
      thruster_prefix: ''
      use_gz_plugin: true
    use_sim_time: true

