cmd_thruster1_steering:
    type: std_msgs/Float64
    angle:
        min: -pi/4
        max: pi/4
        to: data
cmd_thruster2_steering:
    type: std_msgs/Float64
    angle:
        min: -pi/4
        max: pi/4
        to: data
cmd_thruster3_steering:
    type: std_msgs/Float64
    angle:
        min: -pi/4
        max: pi/4
        to: data
cmd_thruster4_steering:
    type: std_msgs/Float64
    angle:
        min: -pi/4
        max: pi/4
        to: data
