cmd_thruster1_steering:
    type: std_msgs/Float64
    angle:
        min: 0
        max: -pi/2
        to: data
cmd_thruster2_steering:
    type: std_msgs/Float64
    angle:
        min: 0
        max: pi/2
        to: data
cmd_thruster3_steering:
    type: std_msgs/Float64
    angle:
        min: 0
        max: pi/2
        to: data
cmd_thruster4_steering:
    type: std_msgs/Float64
    angle:
        min: 0
        max: -pi/2
        to: data
